version: "3.8"
services:
  tailscale:
    image: tailscale/tailscale:stable
    container_name: tailscale
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /appdata/tailscale/state:/var/lib/tailscale
    environment:
      - TS_HOSTNAME=homeserver
      # Se quiseres gateway da LAN:
      # - TS_ROUTES=192.168.1.0/24
      # - TS_EXTRA_ARGS=--accept-routes
    command: >
      tailscaled
      --state=/var/lib/tailscale/tailscaled.state
      --socket=/run/tailscale/tailscaled.sock
      --tun=tailscale0
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"